import { useEffect } from "react";

import { useRouter } from "@/hooks";

// @ts-expect-error types generated by react-router
import type { Route } from "./+types/import-page";

export function meta({}: Route.MetaArgs) {
   return [];
}

export default function ImportPage() {
   const { search } = useRouter();

   useEffect(() => {}, [search.importMethod]);
   return <div>Dashboard</div>;
}
