import { useLocation } from "react-router";

// @ts-expect-error types generated by react-router
import type { Route } from "./+types/import-page";

export function meta({}: Route.MetaArgs) {
   return [];
}
export namespace ImportPage {
   export type State = {
      importType: "files" | "folder";
   };
}

export default function ImportPage() {
   const { state } = useLocation();
   return <div>Dashboard</div>;
}
