// @ts-expect-error types generated by react-router
import type { Route } from "./+types/dashboard";

export function meta({}: Route.MetaArgs) {
   return [];
}

export default function DashboardPage() {
   return <div>Dashboard</div>;
}
