// @ts-expect-error types generated by react-router
import type { Route } from "./+types/settings";

export function meta({}: Route.MetaArgs) {
   return [];
}

export default function SettingsPage() {
   return <div>Settings</div>;
}
