import { useMemo, useState } from "react";
import { useNavigate } from "react-router";

import { LibraryCard, WelcomeCard } from "@/modules/wizard/components/";
import { useSettingsStore } from "@/stores/settings-store";

// @ts-expect-error types generated by react-router
import type { Route } from "./+types/wizard-page";

export function meta({}: Route.MetaArgs) {
   return [];
}

export namespace WizardPage {
   export type CardProps = {
      nextStep: () => void;
      previousStep: () => void;
      finish: () => void;
   };
}

export default function WizardPage() {
   const [step, setStep] = useState(0);
   const navigate = useNavigate();

   const { setFlag } = useSettingsStore();
   const cardProps = useMemo<WizardPage.CardProps>(
      () => ({
         nextStep: () => setStep((prev) => prev + 1),
         previousStep: () => setStep((prev) => Math.max(prev - 1, 0)),
         finish: () => {
            setFlag("isFirstRun", false);
            navigate("/");
         },
      }),
      [setStep]
   );

   return (
      <div className="h-full w-full flex flex-start flex-col items-center justify-center gap-4">
         {step === 0 && <WelcomeCard {...cardProps} />}
         {step === 1 && <LibraryCard {...cardProps} />}
      </div>
   );
}
