import { ObjectPath } from "@/lib/object-path";

import { FFprobeSuccessResult } from "../types/ffprobe";

export const fieldMappings = {
   title: [
      "format.tags.title",
      "format.tags.TITLE",
      "format.tags.©nam",
      "format.tags.audible_title",
      "format.tags.album",
      "format.tags.ALBUM",
   ],
   authors: [
      "format.tags.author",
      "format.tags.audible_author",
      "format.tags.©ART",
      "format.tags.artist",
      "format.tags.ARTIST",
      "format.tags.album_artist",
   ],
   narrators: [
      "format.tags.narrator",
      "format.tags.NARRATOR",
      "format.tags.audible_narrator",
      "format.tags.performer",
      "format.tags.PERFORMER",
      "format.tags.reader",
      "format.tags.READER",
      "format.tags.composer",
      "format.tags.COMPOSER",
      "format.tags.artist",
      "format.tags.ARTIST",
      "format.tags.©ART",
      "format.tags.©nrt",
      "format.tags.audible_reader",
      "format.tags.audible_performer",
   ],
   genres: [
      "format.tags.GENRE",
      "format.tags.genre",
      "format.tags.©gen",
      "format.tags.audible_genre",
   ],
   audibleAsin: [
      "format.tags.audible_asin",
      "format.tags.ASIN",
      "format.tags.asin",
   ],
   isbn: [
      "format.tags.isbn",
      "format.tags.ISBN",
      "format.tags.book_id",
      "format.tags.bookid",
      "format.tags.identifier",
      "format.tags.IDENTIFIER",
   ],
   description: [
      "format.tags.description",
      "format.tags.comment",
      "format.tags.synopsis",
      "format.tags.summary",
      "format.tags.DESCRIPTION",
      "format.tags.COMMENT",
      "format.tags.SYNOPSIS",
      "format.tags.audible_description",
   ],
   releaseDate: [
      "format.tags.date",
      "format.tags.DATE",
      "format.tags.©day",
      "format.tags.year",
      "format.tags.YEAR",
      "format.tags.release_date",
      "format.tags.released",
      "format.tags.publication_date",
      "format.tags.pubdate",
      "format.tags.audible_release_date",
   ],
   publisher: [
      "format.tags.publisher",
      "format.tags.PUBLISHER",
      "format.tags.audible_publisher",
   ],
   seriesTitle: [
      "format.tags.series",
      "format.tags.SERIES",
      "format.tags.album",
      "format.tags.ALBUM",
      "format.tags.series_name",
      "format.tags.SERIES_NAME",
      "format.tags.book_series",
      "format.tags.BOOK_SERIES",
      "format.tags.©alb",
   ],
   seriesOrder: [
      "format.tags.series_part",
      "format.tags.SERIES_PART",
      "format.tags.series_index",
      "format.tags.SERIES_INDEX",
      "format.tags.series_number",
      "format.tags.SERIES_NUMBER",
      "format.tags.book_number",
      "format.tags.BOOK_NUMBER",
      "format.tags.number_in_series",
      "format.tags.NUMBER_IN_SERIES",
      "format.tags.part",
      "format.tags.PART",
      "format.tags.track",
      "format.tags.TRACK",
      "format.tags.©tvs",
   ],
   seriesSubtitle: [
      "format.tags.series_subtitle",
      "format.tags.SERIES_SUBTITLE",
      "format.tags.subtitle",
      "format.tags.SUBTITLE",
      "format.tags.subseries",
      "format.tags.SUBSERIES",
      "format.tags.series_description",
      "format.tags.SERIES_DESCRIPTION",
      "format.tags.©sst",
   ],
} as const satisfies Record<string, ObjectPath<FFprobeSuccessResult>[]>;
