// @ts-expect-error types generated by react-router
import type { Route } from "./+types/genres";

export function meta({}: Route.MetaArgs) {
   return [];
}

export default function Genres() {
   return <div>Genres</div>;
}
