// @ts-expect-error types generated by react-router
import type { Route } from "./+types/library";

export function meta({}: Route.MetaArgs) {
   return [];
}

export default function Library() {
   return <div>Library</div>;
}
