import { useMemo, useState } from "react";

import { LibraryCard, WelcomeCard } from "@/modules/wizard/components/";

// @ts-expect-error types generated by react-router
import type { Route } from "./+types/wizard";

export function meta({}: Route.MetaArgs) {
   return [];
}

export namespace Wizard {
   export type CardProps = {
      nextStep: () => void;
      previousStep: () => void;
   };
}

export default function Wizard() {
   const [step, setStep] = useState(0);
   const cardProps = useMemo<Wizard.CardProps>(
      () => ({
         nextStep: () => setStep((prev) => prev + 1),
         previousStep: () => setStep((prev) => Math.max(prev - 1, 0)),
      }),
      [setStep]
   );

   return (
      <div className="h-full w-full flex flex-start flex-col items-center justify-center gap-4">
         {step === 0 && <WelcomeCard {...cardProps} />}
         {step === 1 && <LibraryCard {...cardProps} />}
      </div>
   );
}
